var $=jQuery;(function($,undefined){'use strict';$(document).foundation();$(document).ready(function(){$('#team-flexslider').flexslider({slideshow:false,controlNav:false});$('.flexslider').flexslider({slideshow:true,slideshowSpeed:2000,controlNav:false});var isMobile=function(){return(Dom.window.width()<=768);};var Dom={window:$(window),body:$('body'),header:$('#header'),content:$('#content'),sidebar:$('#sidebar'),nav:$('#main-nav'),items:$('.main-nav-item','#main-nav'),hamburger:$('#hamburger'),searchInput:$('#search-input'),searchButton:$('#search-button'),sidebarFeatured:$('.featured_widget','#sidebar'),footer:$('#footer')}
var BoutiqueHack=(function(){var Cache={shop:$('#boutique-shop'),brokenTabs:$('.shortcode-panel','#boutique-shop')}
function init(){Dom.window.resize(function(){if(Cache.brokenTabs.is(":visible")){Cache.shop.hide();showOnResizeEnd();}});}
function showOnResizeEnd(){clearTimeout(window.endResizeTimer);window.endResizeTimer=setTimeout(function(){Cache.shop.show();},250);}
return{init:init}})();var Boutique=function(){var Cache={shop:$('#boutique-shop'),tabs:$('.tab-item','#boutique-shop-tabs'),heading:$('#boutique-shop-heading')}
function init(){Cache.shop.isotope({itemSelector:'.boutique-shop-item',filter:'.lcfav',masonry:{}});Cache.tabs.click(filter);Cache.heading.click(filter);}
function filter(){var $this=$(this),filter=$this.data('filter');if(!$this.hasClass('is-active')){Cache.tabs.filter('.is-active').removeClass('is-active');$this.addClass('is-active');}
Cache.shop.isotope({filter:filter})}
return{init:init}}();var ScrollBinder=function(){var Cache={position:Dom.window.scrollTop(),difference:0,scrollSensitivity:300,sidebarTop:0};var scrollUpEvents=function(){Header.show();};var scrollDownEvents=function(){var treshold=isMobile()?500:1800;if(Cache.position>treshold){Menu.hideSearch();Header.hide();}};var pageHeightEvents=function(){var treshold=isMobile()?150:220;if(Cache.position>treshold){Header.minimize();}else{Header.maximize();}};var scrollUpdate=function(){var newPosition=Dom.window.scrollTop();Cache.difference+=Cache.position- newPosition;pageHeightEvents();if(newPosition>Cache.position){if(Cache.difference>0){Cache.difference=0;}else if(Cache.difference<-Cache.scrollSensitivity){scrollDownEvents();}}else if(newPosition<Cache.position){if(Cache.difference<0){Cache.difference=0;}else if(Cache.difference>Cache.scrollSensitivity){scrollUpEvents();}}
Sidebar.updatePosition(Cache.position);Cache.position=newPosition;};var init=function(){Cache.scrollInterval=setInterval(scrollUpdate,10);};return{init:init}}();var Menu=function(){var Cache={placeholder:null};var init=function(){Dom.items.click(toggleItem);Dom.hamburger.click(toggleMenu);Dom.searchButton.click(toggleSearch);Dom.searchInput.focus(hideSearchPlaceholder);Dom.searchInput.blur(showSearchPlaceholder);};var toggleMenu=function(){Dom.nav.fadeToggle(300);Dom.header.toggleClass('mobile-menu-visible');Dom.hamburger.find('img').fadeToggle(200);Dom.footer.toggle();};var toggleSearch=function(event){if(!Dom.searchInput.val()&&isMobile()){event.preventDefault();Dom.searchInput.fadeToggle();}};var hideSearch=function(){if(isMobile()){Dom.searchInput.fadeOut(100);}};var hideSearchPlaceholder=function(){var $this=$(this);Cache.placeholder=$this.attr("placeholder");$this.attr("placeholder","");};var showSearchPlaceholder=function(){var $this=$(this);var placeholder=(Cache.placeholder)?Cache.placeholder:"Search";$this.attr("placeholder",placeholder);}
var toggleItem=function(event){var $this=$(this);if((event.pageX- $this.offset().left>$this.width()/ 2) // Right half of item
&&$(event.target).parent().hasClass('has-sub-menu')&&isMobile()){event.preventDefault();($this.hasClass('active'))?hideItem($this):showItem($this);}};var showItem=function($this){hideItem(Dom.items.filter('.active'));$this.addClass('active').find('.sub-menu').slideDown();};var hideItem=function($target){$target.removeClass('active').find('.sub-menu').slideUp();};return{init:init,hideSearch:hideSearch}}();var Header=function(){var Cache={minimized:false};var show=function(){Dom.header.removeClass('scroll-hidden');};var hide=function(){Dom.header.addClass('scroll-hidden');};var minimize=function(){if(!Cache.minimized&!isMobile()){Dom.header.animate({opacity:'0'},150,function(){Dom.header.toggleClass('small-version');Dom.header.stop().animate({opacity:'1'},300);});Cache.minimized=true;}};var maximize=function(){show();if(Cache.minimized&!isMobile()){Dom.header.animate({opacity:'0'},150,function(){Dom.header.toggleClass('small-version');Dom.header.stop().animate({opacity:'1'},300);});Cache.minimized=false;}};return{hide:hide,show:show,minimize:minimize,maximize:maximize}}();var Sidebar=function(){var Cache={isEnabled:false,widget:$('.featured_widget','#sidebar')};var updatePosition=function(position){if(!Cache.isEnabled||isMobile()){return;}
var $elementAbove=Cache.widget.prev();var distanceToTop=$elementAbove.offset().top+ $elementAbove.height()- 110;Cache.sidebarWidth=Dom.sidebar.width();if(distanceToTop<Math.abs(position)){Cache.widget.addClass('pinned').css('width',Cache.sidebarWidth);}else{Cache.widget.removeClass('pinned');}};var init=function(){if(Cache.widget.length){Cache.isEnabled=true;}}
return{updatePosition:updatePosition,init:init}}();var StayConnectedWidget=function(){var Cache={widget:$('#stay-connected-widget'),button:$('#stay-connected-button'),socialMedia:$('.social-media','#stay-connected-widget')};var hide=function($this){$this.removeClass('active').html('Expand');Cache.socialMedia.slideUp()};var show=function($this){$this.addClass('active').html('Hide');;Cache.socialMedia.slideDown();};var toggleSocialMedia=function(){var $this=$(this);if($this.hasClass('active')){hide($this);}else{show($this);}};var init=function(){Cache.button.click(toggleSocialMedia)};return{init:init}}();var CategoriesWidget=function(){var Cache={item:$('.widget.widget_categories > ul > li.cat-item','#sidebar'),parentItem:null}
var toggleChildren=function(event){event.preventDefault();var $thisParent=$(this).parent();if($thisParent.hasClass('open')){$thisParent.removeClass('open').find('.children').slideUp();}else{Cache.parentItem.filter('.open').removeClass('open').find('.children').slideUp();$thisParent.addClass('open').find('.children').slideDown();}}
var assignParentItems=function(){Cache.item.each(function(i){var $this=$(this);if($this.find('.children').length){$this.addClass('has-children').prepend('<div class="icon"></div>');}
if(i+ 1==Cache.item.length){Cache.parentItem=Cache.item.filter('.has-children');Cache.parentItem.find('> .icon').click(toggleChildren);}});};var init=function(){assignParentItems();};return{init:init}}();var HtmlCloner=function(){var Cache={}
var captureClones=function(){Cache.sponsor=Dom.sidebar.find('.sponsor_widget');Cache.newsletter=Dom.sidebar.find('.newsletter_widget');putClones();};var putClones=function(){Dom.content.find('.hero-post').after(Cache.sponsor.html());Dom.content.find('.must-reads').after(Cache.newsletter.html());};var init=function(){if(Dom.body.hasClass('home')){captureClones();}};return{init:init}}();Menu.init();ScrollBinder.init();Sidebar.init();StayConnectedWidget.init();CategoriesWidget.init();HtmlCloner.init();if($('#boutique-shop').length>0){BoutiqueHack.init();}});})(jQuery);
